### ISSUE TITLE
configure a prod env

### ISSUE THREAD

**Issue by pdougall1** [atlanta-ember-org/atlanta-ember#4]
Currently we only have a staging env that is scoped to `atl-ember-staging/`.  This is because of the way our current ember-cli-deploy addons work with S3, making it necessary to append the bucket name to the url.  There may be some working around with our deployment to get it to work well without the bucket name.

Might require https://github.com/ember-cli-deploy/ember-cli-deploy-s3-index

**Comment by ultimatemonty** [comment]
Closing this since we are now deploying to Heroku from CI.
